services: 
  database: 
    image: postgres:latest 
    restart: always 
    environment: 
      POSTGRES_PASSWORD: verySecretPassword 
      POSTGRES_USER: administrator 
      POSTGRES_DB: todo 
    volumes: 
      #- dbdata:/var/lib/postgresql/data #local
      - ./data/db:/var/lib/postgresql/data #git
    healthcheck: #add healthcheck to make sure its running
      test: ["CMD-SHELL", "pg_isready -U administrator -d todo"]
      interval: 5s
      retries: 10
      start_period: 60s
      timeout: 20s
  app: 
    build: . 
    restart: always 
    environment: 
      SQLALCHEMY_DATABASE_URI: postgresql://administrator:verySecretPassword@database:5432/todo 
    ports: 
      - "6400:6400" 
    depends_on: 
      database:
        condition: service_healthy
        restart: true
#volumes: #local
  #dbdata:
    